kg: env(KG)
endpoint: env(ENDPOINT:null)

run_directory: env(RUN)
selection_run: env(SELECTION_RUN:null)

temperature: env(TEMPERATURE:0.4)
min_p: env(MIN_P:null)
top_k: env(TOP_K:null)
top_p: env(TOP_P:0.9)
repeat_penalty: env(REPEAT_PENALTY:null)
do_sample: env(DO_SAMPLE:true)

skeleton_n: env(SKELETON_N:8)
skeleton_top_k: env(SKELETON_TOP_K:3)

selection_top_k: env(SELECTION_TOP_K:10)
autocomplete: env(AUTOCOMPLETE:true)
backtrack: env(BACKTRACK:true)
rerank: env(RERANK:true)
check_empty: env(CHECK_EMPTY:true)

port: env(PORT:6790)
max_connections: env(MAX_CONNECTIONS:10)
max_generation_time: env(MAX_GENERATION_TIME:300)
max_idle_time: env(MAX_IDLE_TIME:300)
log_outputs: env(LOG_OUTPUTS:null)
