PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT ?id ?value ?tags WHERE {
  # Get ids and their score
  {
    SELECT ?id (MAX(?sitelinks) AS ?score) WHERE {
      ?id rdf:type wikibase:Item .

      {
        ?id @en@rdfs:label ?l .
      } UNION {
        ?id @fr@rdfs:label ?l.
      } UNION {
        ?id @de@rdfs:label ?l.
      } UNION {
        ?id @es@rdfs:label ?l.
      } UNION {
        ?id @pt@rdfs:label ?l.
      } UNION {
        ?id @pt@rdfs:label ?l.
      } UNION {
        ?id @nl@rdfs:label ?l.
      } UNION {
        ?id @ru@rdfs:label ?l.
      }

      MINUS {
        ?id wdt:P31/wdt:P279* wd:Q17442446
      }

      OPTIONAL { ?id ^schema:about/wikibase:sitelinks ?sitelinks }
    } GROUP BY ?id
  }

  OPTIONAL {
    {
      # Get label
      ?id @{LANG}@rdfs:label ?value .
      BIND("main" AS ?tags)
    } UNION {
      # Get aliases
      ?id @{LANG}@skos:altLabel ?value .
    }
  }
}
ORDER BY DESC(?score) ?id DESC(?tags)
