model: env(MODEL:gpt-5-mini)
model_provider: env(MODEL_PROVIDER:openai/responses)
model_endpoint: env(MODEL_ENDPOINT:null)
model_api_key: env(MODEL_API_KEY:null)
model_kwargs:
  reasoning:
    effort: env(REASONING_EFFORT:null)
    summary: env(REASONING_SUMMARY:null)

seed: env(SEED:22)

temperature: env(TEMPERATURE:1.0)
top_p: env(TOP_P:1.0)
api: env(API:null)
