model: env(MODEL:Qwen/Qwen3-30B-A3B-Instruct-2507)
model_provider: env(MODEL_PROVIDER:openai/completions)
model_endpoint: env(MODEL_ENDPOINT:http://helix02:8000/v1)
model_api_key: env(OPENAI_API_KEY:EMPTY)

model_kwargs: {}

tool_choice: env(TOOL_CHOICE:auto)
seed: env(SEED:22)

feedback: env(FEEDBACK:false)
know_before_use: env(KNOW_BEFORE_USE:false)
notes_file: env(NOTES_FILE:null)

sparql_connection_timeout: env(SPARQL_CONNECTION_TIMEOUT:20.0)
sparql_query_timeout: env(SPARQL_QUERY_TIMEOUT:120.0)
sparql_read_timeout: env(SPARQL_READ_TIMEOUT:60.0)

fn_set: env(FN_SET:all)
list_k: env(LIST_K:10)
search_k: env(SEARCH_K:10)
result_max_rows: env(RESULT_MAX_ROWS:10)
result_max_columns: env(RESULT_MAX_COLUMNS:10)

force_examples: env(FORCE_EXAMPLES:null)
random_examples: env(RANDOM_EXAMPLES:false)
num_examples: env(NUM_EXAMPLES:3)

knowledge_graphs:
  - kg: env(KG:doremus)
    example_index: env(KG_EXAMPLES:null)
    entities_type: env(ENTITIES_TYPE:fuzzy)
    properties_type: env(PROPERTIES_TYPE:embedding)
    notes_file: env(KG_NOTES_FILE:null)
    indices: env(KG_INDICES:[])
    info:
      endpoint: env(KG_ENDPOINT:https://doremus.ehrh.art/spqrql)
      headers:
        Accept: application/sparql-results+json
      params:
        default-graph-uri: ""
        format: application/sparql-results+json
        timeout: "0"
        signal_void: "on"
      prefixes:
        efrbroo: http://erlangen-crm.org/efrbroo/
        ecrm: http://erlangen-crm.org/current/
        foaf: http://xmlns.com/foaf/0.1/
        rdfs: http://www.w3.org/2000/01/rdf-schema#
        rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
        dct: http://purl.org/dc/terms/
        skos: http://www.w3.org/2004/02/skos/core#
