PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?id ?value ?tags WHERE {
  # Get ids and their frequencies for score
  { SELECT ?id (COUNT(?id) AS ?score) WHERE { ?s ?id ?o } GROUP BY ?id } 

  {
    # Get label as main field
    ?id rdfs:label ?value
    BIND("main" AS ?tags)
    FILTER(LANG(?value) = "en")
  } UNION {
    # Get aliases
    ?id skos:altLabel ?value
    FILTER(LANG(?value) = "en")
  } UNION {
    # Properties often do not have labels, so make IRI itself
    # searchable by binding it to value directly; the indexer
    # will extract the local name from the full IRI, so no
    # need to do it manually here
    BIND(?id AS ?value)
  }
} ORDER BY DESC(?score) ?id DESC(?tags)
